<!DOCTYPE html>
<html>
<head>
    <title>Crear nueva tarea</title>
    <link href="https://cdn.tailwindcss.com" rel="stylesheet">
</head>
<body>
    <h1>Crear nueva tarea</h1>

    <form method="POST" action="createTask">
        <label for="name">Nombre tarea:</label>
        <input class="border rounded p-1" type="text" id="name" name="name" required><br>

        <label for="user">Encargado:</label>
        <input class="border rounded p-1" type="text" id="user" name="user" required><br>

        <input class="bg-blue-400 hover:bg-blue-700 text-white font-bold px-3 py-1 rounded m-1" type="submit" value="Crear tarea">
    </form>

    <a class="bg-blue-400 hover:bg-blue-700 text-white font-bold px-3 py-1 rounded m-1" href="<?php echo WEB_ROOT; ?>">Volver al menú</a>
</body>
</html>
