<!DOCTYPE html>
<html>
<head>
    <title>Crear nueva tarea</title>
</head>
<body>
    <h1>Crear nueva tarea</h1>

    <form method="POST" action="createTask">
        <label for="name">Nombre tarea:</label>
        <input type="text" id="name" name="name" required><br>

        <label for="user">Encargado:</label>
        <input type="text" id="user" name="user" required><br>

        <input type="submit" value="Crear tarea">
    </form>
</body>
<a href=<?php echo WEB_ROOT; ?>>Volver al menu</a>

</html>
