<!DOCTYPE html>
<html>
<head>
    <title>Crear nueva tarea</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-white-200 flex justify-center items-center h-screen">
    <div class="container w-80 sm:w-auto bg-pink-200 p-10 rounded shadow-2xl text-center">
        <h1 class="text-4xl font-bold mb-4">Crear nueva tarea</h1>

        <form method="POST" action="createTask">
            <label for="name" class="block text-gray-700 font-semibold mb-2">Nombre tarea:</label>
            <input class="border rounded px-3 py-2 w-full mb-4" type="text" id="name" name="name" required>

            <label for="user" class="block text-gray-700 font-semibold mb-2">Encargado:</label>
            <input class="border-gray-200 rounded px-3 py-2 w-full mb-4" type="text" id="user" name="user" required>

            <input class="bg-pink-700 hover:bg-pink-700 text-white font-bold px-4 py-2 rounded cursor-pointer" type="submit" value="Crear tarea">
        </form>

        <a class="bg-pink-700 hover:bg-pink-700 text-white font-bold px-4 py-2 rounded mt-4 inline-block" href="<?php echo WEB_ROOT; ?>">Volver al menú</a>
    </div>
</body>
</html>

