<!DOCTYPE html>
<html>
<head>
    <title>Tarea Eliminada</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    <div class="container w-80 sm:w-auto mx-auto mt-10 bg-pink-200 p-10 rounded shadow-2xl">
            <h1 class="text-3xl font-bold text-center m-10">Tarea eliminada</h1>
            <a class="bg-pink-700 hover:bg-pink-900 text-white font-bold px-3 py-1 rounded" href="<?php echo WEB_ROOT ?>">Volver al menu</a>
    </div>    
</body>
</html>
