<!DOCTYPE html>
<html>
<head>
    <title>Tarea Eliminada</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-white-200 flex justify-center items-center h-screen">
    <div class="container w-80 sm:w-auto bg-pink-200 p-5 rounded shadow-2xl text-center relative">
        <h1 class="text-3xl font-bold text-center m-10 mt-5">Tarea eliminada</h1>
        <img src="<?php echo WEB_ROOT . "/images/delete.png" ?>" class="mx-auto mt-5 mb-4 w-30 h-36" />
        <a class="bg-pink-700 hover:bg-pink-900 text-white font-bold px-3 py-1 rounded float-right" href="<?php echo WEB_ROOT ?>">Volver al menú</a>
    </div>    
</body>
</html>
