<!DOCTYPE html>
<html>
<head>
    <title>Menú</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    <div class="container w-80 sm:w-auto mx-auto mt-10 bg-slate-200 p-10 rounded shadow-2xl">
        <h1 class="text-3xl font-bold text-center">ToDo Application</h1>
        <h1 class="text-3xl font-bold text-center m-10">Menú</h1>
        <div class="flex justify-center">
            <p class="my-5">
                <a class="bg-blue-400 hover:bg-blue-700 text-white font-bold px-3 py-1 rounded m-5 text-center" href="createTask">Crear nueva tarea</a>
            </p>
            <p class="my-5">
                <a class="bg-blue-400 hover:bg-blue-700 text-white font-bold px-3 py-1 rounded m-5 text-center" href="showAllTasks">Ver todas las tareas</a>
            </p>
        </div>
        <div class="m-10">
            <form action="showTask" method="get" class="my-5">
                <label for="task_id">Buscar tarea por ID:</label>
                <input class="border rounded" type="text" id="task_id" name="id" required>
                <input class="bg-blue-400 hover:bg-blue-700 text-white font-bold px-3 py-1 rounded"type="submit" value="Buscar">
            </form>
            <form action="updateTask" method="post" class="my-5">
                <label for="id">ID de la tarea:</label>
                <input class="border rounded" type="text" id="id" name="id" required>
                <label for="status">Estado:</label>
                <select id="status" name="status">
                <option value="Pendiente" <?php echo ['status'] === 'Pendiente' ? 'selected' : ''; ?>>Pendiente</option>
                <option value="En Ejecucion" <?php echo['status'] === 'En Ejecucion' ? 'selected' : ''; ?>>En ejecución</option>
                <option value="Terminada" <?php echo ['status'] === 'Terminada' ? 'selected' : ''; ?>>Terminada</option>
            </select><br>
                <input class="bg-blue-400 hover:bg-blue-700 text-white font-bold px-3 py-1 rounded" type="submit" value="Actualizar">
            </form>

            <form action="deleteTask" method="get" class="my-5">
                <label for="task_id">Eliminar tarea por ID:</label>
                <input class="border rounded" type="text" id="task_id" name="id" required>
                <input class="bg-blue-400 hover:bg-blue-700 text-white font-bold px-3 py-1 rounded" type="submit" value="Eliminar">
            </form>
        </div>
    </div>
</body>
</html>
