<!DOCTYPE html>
<html>
<head>
    <title>Menú</title>
</head>
<body>
    <h1>Menú</h1>

    <p><a href="createTask">Crear nueva tarea</a></p>
    
    <p><a href="showAllTasks">Ver todas las tareas</a></p>

    <form action="showTask" method="get">
        <label for="task_id">Buscar tarea por ID:</label>
        <input type="text" id="task_id" name="id" required>
        <input type="submit" value="Buscar">
    </form>
    <form action="updateTask" method="get">
        <label for="task_id">Actualizar tarea por ID:</label>
        <input type="text" id="task_id" name="id" required>
        <input type="submit" value="Buscar">
    </form>
    <form action="deleteTask" method="get">
        <label for="task_id">Eliminar tarea por ID:</label>
        <input type="text" id="task_id" name="id" required>
        <input type="submit" value="Buscar">
    </form>
</body>
</html>
