<!DOCTYPE html>
<html>
<head>
    <title>Lista de tareas</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-white-200 flex justify-center items-center h-screen">
    <div class="container w-80 sm:w-auto bg-pink-200 p-5 rounded shadow-2xl text-center relative">
        <img src="<?php echo WEB_ROOT . "/images/vertareas.png" ?>" class="mx-auto mt-0 mb-9 w-30 h-36" />
        <ul>
            <?php foreach ($this->tasks as $task): ?>
                <li class="mb-9">
                    <strong>ID:</strong> <?php echo $task['id']; ?> |
                    <strong>Tarea:</strong> <?php echo $task['name']; ?> |
                    <strong>Autor:</strong> <?php echo $task['user']; ?> |
                    <strong>Estado:</strong> <?php echo $task['status']; ?> |
                    <strong>Día inicio:</strong> <?php echo $task['startTime']; ?> |
                    <strong>Día final:</strong> <?php echo $task['endTime']; ?>
                </li>
            <?php endforeach; ?>
        </ul>
        <a class="bg-pink-700 hover:bg-pink-700 text-white font-bold px-4 py-2 rounded mt-4 inline-block float-right" href="<?php echo WEB_ROOT ?>">Volver al menú</a>
    </div>
</body>
</html>
