<!DOCTYPE html>
<html>
<head>
    <title>Lista de tareas</title>
</head>
<body>
    <h1>Lista de tareas</h1>
    <ul>
        <?php foreach ($this->tasks as $task): ?>
            <li>     
                <strong>ID:</strong> <?php echo $task['id']; ?> |
                <strong>Tarea:</strong> <?php echo $task['name']; ?> |
                <strong>Autor:</strong> <?php echo $task['user']; ?> |
                <strong>Estado:</strong> <?php echo $task['status']; ?>
                <strong>Dia inicio:</strong> <?php echo $task['startTime']; ?> |
                <strong>Dia final:</strong> <?php echo $task['endTime']; ?>
            </li>
        <?php endforeach; ?>
    </ul>
    <a href="<?php echo WEB_ROOT ?>">Volver al menu</a>
</body>
</html>
