<!DOCTYPE html>
<html>
<head>
    <title>Detalles de la tarea</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-white-200 flex justify-center items-center h-screen">
    <div class="container mx-auto p-4 bg-pink-200 rounded shadow-lg text-center">
        <h1 class="text-4xl font-bold mb-4">Detalles de la tarea</h1>
        
        <p><strong>Nombre de la tarea:</strong> <?php echo $this->task['name']; ?></p>
        <p><strong>Autor de la tarea:</strong> <?php echo $this->task['user']; ?></p>
        <p><strong>Estado:</strong> <?php echo $this->task['status']; ?></p>
        <p><strong>Hora de inicio:</strong> <?php echo $this->task['startTime'] ?? 'No especificado'; ?></p>
        <p><strong>Hora de finalización:</strong> <?php echo $this->task['endTime'] ?? 'No especificado'; ?></p>

        <a class="bg-pink-700 hover:bg-bg-pink-700 text-white font-bold px-4 py-2 rounded mt-4 inline-block" href="<?php echo WEB_ROOT; ?>">Volver al menú</a>
    </div>
</body>
</html>
