<?php $task = $this->task; $taskId = $this->taskId ?>
<!DOCTYPE html>
<html>
<head>
    <title>Actualizar tarea</title>
</head>
<body>
    <h1>Actualizar tarea</h1>
        <form method="POST" action="updateTask">
            <input type="hidden" name="id" value="<?php echo $this->task['id']; ?>">
            <label for="name">Nombre tarea:</label>
            <input type="text" id="name" name="name" value="<?php echo $this->task['name']; ?>" required><br>

            <label for="user">Encargado:</label>
            <input type="text" id="user" name="user" value="<?php echo $this->task['user']; ?>" required><br>

            <label for="status">Estado:</label>
            <select id="status" name="status">
                <option value="Pendiente" <?php echo $this->task['status'] === 'Pendiente' ? 'selected' : ''; ?>>Pendiente</option>
                <option value="En Ejecucion" <?php echo $this->task['status'] === 'En Ejecucion' ? 'selected' : ''; ?>>En ejecución</option>
                <option value="Terminada" <?php echo $this->task['status'] === 'Terminada' ? 'selected' : ''; ?>>Terminada</option>
            </select><br>

            <input type="submit" name="update" value="Actualizar tarea">
        </form>
    <a href="<?php echo WEB_ROOT ?>">Volver al menu</a>
</body>
</html>

