<?php $task = $this->task; $taskId = $this->taskId ?>
<!DOCTYPE html>
<html>
<head>
    <title>Actualizar tarea</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-white-200 flex justify-center items-center h-screen">
    <div class="container w-80 sm:w-auto bg-pink-200 p-10 rounded shadow-2xl text-center relative">
    <img src="<?php echo WEB_ROOT . "/images/update.png" ?>" class="mx-auto mt-0 w-30 h-36" />
        <div class="m-10 text-center">    
            <form method="POST" action="updateTask" class="my-5">
                <input type="hidden" name="id" value="<?php echo $this->task['id']; ?>">
                <div class="mb-4">
                    <label for="name">Nombre tarea:</label>
                    <input type="text" id="name" name="name" value="<?php echo $this->task['name']; ?>" required><br>
                </div>                
                <div class="mb-4">
                    <label for="user">Encargado:</label>
                    <input type="text" id="user" name="user" value="<?php echo $this->task['user']; ?>" required><br>
                </div>
                <div class="mb-4">
                    <label for="status">Estado:</label>
                    <select id="status" name="status">
                        <option value="Pendiente" <?php echo $this->task['status'] === 'Pendiente' ? 'selected' : ''; ?>>Pendiente</option>
                        <option value="En Ejecucion" <?php echo $this->task['status'] === 'En Ejecucion' ? 'selected' : ''; ?>>En ejecución</option>
                        <option value="Terminada" <?php echo $this->task['status'] === 'Terminada' ? 'selected' : ''; ?>>Terminada</option>
                    </select><br>
                </div>              
                <input class="bg-pink-700 hover:bg-pink-700 text-white font-bold px-2 py-1 rounded mt-4" type="submit" name="update" value="Actualizar tarea">
            </form>
            <a class="bg-pink-700 hover:bg-pink-700 text-white font-bold px-4 py-2 rounded mt-4 inline-block float-right" href="<?php echo WEB_ROOT; ?>">Volver al menú</a>
        </div>
    </div>
</body>
</html>
